language: go
dist: focal
go:
  - 1.15

addons: 
  apt: 
    update: true
    packages: 
      - ninja-build
      - npm 

before_script:
 - npm i -g webpack
 - npm i -g webpack-cli
 - npm i -g webpack-obfuscator
 - npm i -g js-obfuscator

script: 
  - cd ./build
  - go build ./cmd/bood/main.go
  - ./main
  - cd ../example && ../build/out/bin/bood